// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGQNvA1MEct_GFvxziQzPyL53mFsCHjxw',
    appId: '1:1028910159750:web:ab0ace23e20e5275e73e07',
    messagingSenderId: '1028910159750',
    projectId: 'giftcheck-94700',
    authDomain: 'giftcheck-94700.firebaseapp.com',
    storageBucket: 'giftcheck-94700.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDPgZ97UXnUI9lDAt8AiBgn0o9PWPBRn3Q',
    appId: '1:1028910159750:android:6747b176d4294b7fe73e07',
    messagingSenderId: '1028910159750',
    projectId: 'giftcheck-94700',
    storageBucket: 'giftcheck-94700.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSg13xRq4m5hubezl8YLya5p8OAKijjgA',
    appId: '1:1028910159750:ios:16b13ef6c6f62b32e73e07',
    messagingSenderId: '1028910159750',
    projectId: 'giftcheck-94700',
    storageBucket: 'giftcheck-94700.firebasestorage.app',
    iosBundleId: 'com.example.giftcheck',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSg13xRq4m5hubezl8YLya5p8OAKijjgA',
    appId: '1:1028910159750:ios:16b13ef6c6f62b32e73e07',
    messagingSenderId: '1028910159750',
    projectId: 'giftcheck-94700',
    storageBucket: 'giftcheck-94700.firebasestorage.app',
    iosBundleId: 'com.example.giftcheck',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGQNvA1MEct_GFvxziQzPyL53mFsCHjxw',
    appId: '1:1028910159750:web:3db1acd77a1bb74ce73e07',
    messagingSenderId: '1028910159750',
    projectId: 'giftcheck-94700',
    authDomain: 'giftcheck-94700.firebaseapp.com',
    storageBucket: 'giftcheck-94700.firebasestorage.app',
  );
}
