import { readFileSync } from 'node:fs';
import assert from 'node:assert/strict';
import { initializeTestEnvironment, assertFails, assertSucceeds } from '@firebase/rules-unit-testing';
import { doc, setDoc, getDoc, updateDoc, deleteDoc, writeBatch, serverTimestamp, Timestamp, runTransaction } from 'firebase/firestore';
const env = await initializeTestEnvironment({projectId:'demo-giftcheck-vouchers', firestore:{host:'127.0.0.1',port:8787,rules:readFileSync(new URL('../../firestore.rules', import.meta.url),'utf8')}});
let passed=0;
async function test(name,fn){await env.clearFirestore();await env.withSecurityRulesDisabled(async ctx=>{for(const [uid,role,active] of [['admin','administrator',true],['local1','local',true],['local2','local',true],['inactive','local',false]]) await setDoc(doc(ctx.firestore(),'accounts',uid),{role,active});});await fn();passed++;console.log('PASS',name);}
const db=u=>env.authenticatedContext(u).firestore();
const code='VA000001';
const card=(uid, overrides={})=>({type:'voucher',code,amount:'50000',remainingAmount:'50000',usedAmount:'0',status:'Activa',expirationDate:Timestamp.fromMillis(Date.now()+86400000),dedication:'',senderName:'',recipientName:'',creatorUid:uid,createdAt:serverTimestamp(),...overrides});
const create=(u,overrides={})=>setDoc(doc(db(u),'giftCards',code),card(u,overrides));
function use(u,amount,{used=amount,remaining=50000-amount,status=remaining===0?'Canjeada':'Parcialmente usada',usage=true}={}){const d=db(u),batch=writeBatch(d),id=doc(d,'giftCardUsages',crypto.randomUUID());batch.update(doc(d,'giftCards',code),{usedAmount:String(used),remainingAmount:String(remaining),status,lastUsageId:id.id,updatedAt:serverTimestamp()});if(usage) batch.set(id,{giftCardCode:code,amountUsed:String(amount),username:u,accountUid:u,usedAt:serverTimestamp()});return batch.commit();}
try {
 await test('Both roles reserve sequential codes; counter cannot reset or delete',async()=>{await assertSucceeds(setDoc(doc(db('local1'),'counters','vouchers'),{lastSequence:1,updatedAt:serverTimestamp()}));await assertSucceeds(setDoc(doc(db('admin'),'counters','vouchers'),{lastSequence:2,updatedAt:serverTimestamp()}));await assertFails(setDoc(doc(db('local2'),'counters','vouchers'),{lastSequence:1,updatedAt:serverTimestamp()}));await assertFails(setDoc(doc(db('inactive'),'counters','vouchers'),{lastSequence:3,updatedAt:serverTimestamp()}));await assertFails(deleteDoc(doc(db('admin'),'counters','vouchers')));});
 await test('Concurrent code reservations are distinct',async()=>{async function reserve(u){const d=db(u),ref=doc(d,'counters','vouchers');let observed=0;for(let attempt=0;;attempt++){try{return await runTransaction(d,async tx=>{const before=await tx.get(ref);observed=before.data()?.lastSequence??0;const next=observed+1;tx.set(ref,{lastSequence:next,updatedAt:serverTimestamp()});return next;});}catch(e){if(attempt>=4 || !['permission-denied','aborted'].includes(e.code))throw e;const latest=await getDoc(ref);if((latest.data()?.lastSequence??0)<=observed)throw e;}}}const values=await Promise.all([reserve('local1'),reserve('local2'),reserve('admin')]);assert.deepEqual(values.sort(),[1,2,3]);});
 await test('Both roles create vouchers',async()=>{await assertSucceeds(create('local1'));await assertSucceeds(setDoc(doc(db('admin'),'giftCards','VA000002'),card('admin',{code:'VA000002'})));});
 await test('Anonymous and inactive users denied',async()=>{await assertFails(setDoc(doc(env.unauthenticatedContext().firestore(),'giftCards',code),card('x')));await assertFails(create('inactive'));});
 await test('Mandatory positive numeric amount and timestamp, even for admin',async()=>{for(const amount of ['','0','abc','1.5','-1','1000000000000']) await assertFails(create('admin',{amount,remainingAmount:amount}));for(const expirationDate of [null,Timestamp.fromMillis(Date.now()-86400000)])await assertFails(create('local1',{expirationDate}));});
 await test('Local cannot create Gift Card or spoof creator',async()=>{await assertFails(setDoc(doc(db('local1'),'giftCards','A000123'),{code:'A000123',amount:'100'}));await assertFails(create('local1',{creatorUid:'admin'}));});
 await test('Partial uses by different locals preserve balance, then redeem',async()=>{await create('local1');await assertSucceeds(use('local2',10000));await assertSucceeds(use('local1',40000,{used:50000,remaining:0}));assert.equal((await getDoc(doc(db('local1'),'giftCards',code))).data().status,'Canjeada');await assertFails(use('local1',1,{used:50001,remaining:0}));});
 await test('Overdraw, reset and absent history denied',async()=>{await create('local1');await assertFails(use('local1',60000));await assertFails(use('local1',100,{remaining:50000}));await assertFails(use('local1',100,{usage:false}));});
 await test('History alone cannot claim a voucher use',async()=>{await create('local1');await assertFails(setDoc(doc(db('local1'),'giftCardUsages','orphan'),{giftCardCode:code,amountUsed:'10',username:'local1',accountUid:'local1',usedAt:serverTimestamp()}));});
 await test('Immutable amount and expiration cannot be changed by local',async()=>{await create('local1');await assertFails(updateDoc(doc(db('local1'),'giftCards',code),{amount:'100000'}));await assertFails(updateDoc(doc(db('local1'),'giftCards',code),{expirationDate:Timestamp.fromMillis(Date.now()+999999999)}));});
 await test('Admin can block/reactivate; local cannot; blocked cannot redeem',async()=>{await create('local1');await assertFails(updateDoc(doc(db('local1'),'giftCards',code),{status:'Bloqueada',updatedAt:serverTimestamp()}));await assertSucceeds(updateDoc(doc(db('admin'),'giftCards',code),{status:'Bloqueada',updatedAt:serverTimestamp()}));await assertFails(use('local1',100));await assertSucceeds(updateDoc(doc(db('admin'),'giftCards',code),{status:'Activa',updatedAt:serverTimestamp()}));await assertSucceeds(use('local1',100));});
 await test('Server prevents expired voucher use',async()=>{await env.withSecurityRulesDisabled(async ctx=>setDoc(doc(ctx.firestore(),'giftCards',code),card('local1',{expirationDate:Timestamp.fromMillis(Date.now()-86400000)})));await assertFails(use('local1',100));});
 await test('Concurrent transactions cannot spend the same balance twice',async()=>{await create('local1');async function spend(u){const d=db(u);return runTransaction(d,async tx=>{const ref=doc(d,'giftCards',code),snap=await tx.get(ref),before=snap.data(),amount=40000;if(Number(before.remainingAmount)<amount)throw new Error('Insufficient balance');const log=doc(d,'giftCardUsages',crypto.randomUUID());tx.update(ref,{usedAmount:String(Number(before.usedAmount)+amount),remainingAmount:String(Number(before.remainingAmount)-amount),status:'Parcialmente usada',lastUsageId:log.id,updatedAt:serverTimestamp()});tx.set(log,{giftCardCode:code,amountUsed:String(amount),username:u,accountUid:u,usedAt:serverTimestamp()});});}const results=await Promise.allSettled([spend('local1'),spend('local2')]);assert.equal(results.filter(x=>x.status==='fulfilled').length,1);assert.equal((await getDoc(doc(db('local1'),'giftCards',code))).data().remainingAmount,'10000');});
 await test('Existing Gift Card creation and partial use remain supported',async()=>{const a=db('admin'),l=db('local1');await assertSucceeds(setDoc(doc(a,'giftCards','A000123'),{code:'A000123',amount:'50000',dedication:'',status:'Activa'}));await assertSucceeds(updateDoc(doc(l,'giftCards','A000123'),{usedAmount:'100',remainingAmount:'49900',status:'Parcialmente usada',updatedAt:serverTimestamp()}));});
 console.log(`${passed} rules tests passed`);
} finally {await env.cleanup();}
